## START: Set by rpmautospec
## (rpmautospec version 0.8.4)
## RPMAUTOSPEC: autorelease, autochangelog
%define autorelease(e:s:pb:n) %{?-p:0.}%{lua:
    release_number = 1;
    base_release_number = tonumber(rpm.expand("%{?-b*}%{!?-b:1}"));
    print(release_number + base_release_number - 1);
}%{?-e:.%{-e*}}%{?-s:.%{-s*}}%{!?-n:%{?dist}}
## END: Set by rpmautospec

# Generated by rust2rpm 27
%bcond check 1

# prevent library files from being installed
%global cargo_install_lib 0

%global crate podman-sequoia
%global crate_version 0.4.0-pqc.3

%if 0%{?rhel}
# RHEL: Use bundled deps as it doesn't ship Rust libraries
%global bundled_rust_deps 1
%global __brp_mangle_shebangs_exclude_from ^/usr/src/debug/.*$
%else
# Fedora: Use only system Rust libraries
%global bundled_rust_deps 0
%endif

Name:           rust-podman-sequoia
Version:        0.4.0~pqc.3
Release:        %autorelease
Summary:        Polyfill to use Sequoia as a signing backend for containers

License:        Apache-2.0
URL:            https://crates.io/crates/podman-sequoia
Source0:        %{crates_source %{crate} %{crate_version}}
# Generated using cargo-vendor-filterer:
#   cargo download %%{crate}==%%{version} > %%{crate}-%%{version}.crate
#   tar xf %%{crate}-%%{version}.crate
#   pushd %%{crate}-%%{version}
#   cargo vendor-filterer --platform x86_64-unknown-linux-gnu \
#                         --platform powerpc64le-unknown-linux-gnu \
#                         --platform aarch64-unknown-linux-gnu \
#                         --platform i686-unknown-linux-gnu \
#                         --platform s390x-unknown-linux-gnu \
#                         --all-features=true
Source1:        %{crate}-%{crate_version}-vendor.tar.xz
# Manually created patch for downstream crate metadata changes
# * default to the OpenSSL crypto backend of sequoia-openpgp
Patch:          podman-sequoia-fix-metadata.diff

%if 0%{?bundled_rust_deps}
BuildRequires:  rust-toolset
# vendored openssl-sys
BuildRequires:  openssl-devel
BuildRequires:  sqlite-devel
%else
BuildRequires:  cargo-rpm-macros >= 26
%endif
BuildRequires:  clang-devel >= 3.5
BuildRequires:  capnproto

%global _description %{expand:
A polyfill to use Sequoia as a signing backend for containers.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# Upstream license specification: Apache-2.0
#
# The build dependencies have the following licenses:
#
#   (MIT OR Apache-2.0) AND Unicode-DFS-2016
#   0BSD OR MIT OR Apache-2.0
#   Apache-2.0
#   Apache-2.0 OR MIT
#   Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT
#   BSD-2-Clause OR Apache-2.0 OR MIT
#   BSD-3-Clause
#   BSL-1.0
#   LGPL-2.0-or-later
#   MIT
#   MIT OR Apache-2.0
#   MIT OR Zlib OR Apache-2.0
#   MPL-2.0
#   Unicode-3.0
#   Unlicense OR MIT
#   Zlib
License:        ((MIT OR Apache-2.0) AND Unicode-DFS-2016) AND (0BSD OR MIT OR Apache-2.0) AND Apache-2.0 AND (Apache-2.0 OR MIT) AND (Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT) AND (BSD-2-Clause OR Apache-2.0 OR MIT) AND BSD-3-Clause AND BSL-1.0 AND LGPL-2.0-or-later AND MIT AND (MIT OR Apache-2.0) AND (MIT OR Zlib OR Apache-2.0) AND MPL-2.0 AND Unicode-3.0 AND (Unlicense OR MIT) AND Zlib
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%license LICENSE.dependencies
%doc README.md
%{_libdir}/libpodman_sequoia.so.*
%{_libdir}/libpodman_sequoia.so
%{_datadir}/containers/podman-sequoia/sequoia.h
%{_datadir}/containers/podman-sequoia/gosequoia.h
%{_datadir}/containers/podman-sequoia/gosequoia.c
%{_datadir}/containers/podman-sequoia/gosequoiafuncs.h

%prep
%autosetup -n %{crate}-%{crate_version} -N %{?bundled_rust_deps:-a1}
%autopatch -M 99 -p1
%if 0%{?bundled_rust_deps}
%cargo_prep -v vendor
%else
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires
%endif

%build
# build script uses environment variables to populate the pkgconfig file
export PREFIX="%{_prefix}"
export LIBDIR="%{_libdir}"
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
# install shared library
mkdir -p %{buildroot}/%{_libdir}
cp -pav target/release/libpodman_sequoia.so %{buildroot}/%{_libdir}/libpodman_sequoia.so.0
# create unversioned symlink
ln -s libpodman_sequoia.so.0 %{buildroot}/%{_libdir}/libpodman_sequoia.so
# install bindings
mkdir -p %{buildroot}/%{_datadir}/containers/podman-sequoia
cp -pav target/release/bindings/*.[ch] %{buildroot}/%{_datadir}/containers/podman-sequoia/

%if %{with check}
%check
# prefer built-in crypto-policies over system settings on the koji builder
export SEQUOIA_CRYPTO_POLICY=/dev/null
# * signature::tests::import_keys may fail on a machine with slow disk I/O
%cargo_test -- -- --skip signature::tests::import_keys
%endif

%changelog
## START: Generated by rpmautospec
* Thu Jun 11 2026 Daiki Ueno <dueno@redhat.com> - 0.4.0~pqc.3-1
- Update to 0.4.0-pqc.3 for LLVM 22 compatibility

* Thu Dec 18 2025 Daiki Ueno <dueno@redhat.com> - 0.4.0~pqc.2-1
- Update to 0.4.0-pqc.2

* Thu Nov 27 2025 Daiki Ueno <dueno@redhat.com> - 0.4.0~pqc.1-1
- Enable PQC algorithms

* Thu Nov 27 2025 Daiki Ueno <dueno@redhat.com> - 0.2.0-2
- Unbundle capnproto

* Mon Aug 25 2025 Daiki Ueno <dueno@redhat.com> - 0.2.0-1
- Update to 0.2.0 release

* Tue Aug 05 2025 Stanislav Zidek <szidek@redhat.com> - 0.1.0-2
- gating setup

* Tue Aug 05 2025 Daiki Ueno <dueno@redhat.com> - 0.1.0-1
- Initial import from Fedora
## END: Generated by rpmautospec
